### ISSUE TITLE
Could you add license

### ISSUE THREAD

**Issue by mage1k99** [mrcodekiddie/shell-sweeties#1]
This is nice but it would be good if

- You would add license
- Proper ReadMe file

https://github.com/praba2210/bash-insulter

could you add comparability for fish ?

**Comment by mrcodekiddie** [comment]
Licence - 👌 Done
ReadMe - 🤖 After few actually usable scripts

Ignore the Bash Insulter ,  using bash itself is insult ( dad joke )

**Comment by mage1k99** [comment]
okay what about the eta for readme update ?

nice joke through
